extends RefCounted
class_name Content
static func men() -> Array:
	return [
		{"id": "adrian", "name": "Adrian", "hidden_type": "resource",
			"surface": "resource", "energy_cost": 3,
			"risk": "Control tendency", "opportunity": "Concrete action if you make him earn it",
			"chat": [{"from": "him", "text": "Saturday night?"},
					 {"from": "you", "text": "Tell me when and where."}],
			"others_chat": [
				{"to": "a colleague", "text": "Can't do Thursday. I'll have the numbers to you Friday 9am — you'll have them."},
				{"to": "his sister", "text": "Booked Mum's flights. Aisle seat like she likes. Don't tell her, let her find out."},
				{"to": "an ex", "text": "I'm not doing the late-night thing. If you want to talk, it's a call, daytime."}]},
		{"id": "evan", "name": "Evan", "hidden_type": "high_sugar",
			"surface": "growth", "energy_cost": 2,
			"risk": "Midnight sugar, no action", "opportunity": "Short spike only",
			"chat": [{"from": "him", "text": "Still awake? Thinking of you."},
					 {"from": "you", "text": "It's late."}],
			"others_chat": [
				{"to": "another girl, 1:14am", "text": "you're not like the others. you actually get me 🌙"},
				{"to": "a third girl, last Tuesday", "text": "you're different. nobody's ever understood me like you do"},
				{"to": "the group chat", "text": "lmaooo I just say what they wanna hear, who's actually showing up tho"}]},
		{"id": "leo", "name": "Leo", "hidden_type": "growth",
			"surface": "false_alpha", "energy_cost": 1,
			"risk": "Ego-sensitive, low spike", "opportunity": "Cheap to observe, long upside",
			"chat": [{"from": "him", "text": "I kept thinking about what you said."},
					 {"from": "you", "text": "Go on."}],
			"others_chat": [
				{"to": "his best friend", "text": "I was loud at the table, I know. Overdid it. Working on it, genuinely."},
				{"to": "a mentor", "text": "You said one line three months ago about compounding patience. I still think about it."},
				{"to": "his brother", "text": "Didn't get the round. It's fair. Going back in better, not louder."}]},
		{"id": "marcus", "name": "Marcus", "hidden_type": "high_sugar",
			"surface": "resource", "energy_cost": 3,
			"risk": "All optics, nothing clears", "opportunity": "None — the bill never lands",
			"chat": [{"from": "him", "text": "Booked the chef's table Friday. Wear something I can show off."},
					 {"from": "you", "text": "Sure."},
					 {"from": "him", "text": "Car gets you at 8. I hate waiting."}],
			"others_chat": [
				{"to": "his assistant", "text": "Cancel the Friday table if she doesn't confirm by noon. Not chasing it."},
				{"to": "another girl, same week", "text": "chef's table Friday if you're free 😏 you'd love it"},
				{"to": "the group chat", "text": "lol I never pay full, comped every time, it's all optics"},
				{"to": "a contact, 3rd week running", "text": "yeah yeah I'll wire it next week, you know I'm good for it"},
				{"to": "his brother", "text": "she's fine for now. not serious. don't bring her up at mum's."}]},
		{"id": "daniel", "name": "Daniel", "hidden_type": "resource",
			"surface": "high_sugar", "energy_cost": 2,
			"risk": "Reads like a line, isn't", "opportunity": "Concrete and boundaried under the corny",
			"chat": [{"from": "him", "text": "good morning beautiful ☀️ thought about you"},
					 {"from": "you", "text": "morning."},
					 {"from": "him", "text": "can't help it. you're trouble 😅"}],
			"others_chat": [
				{"to": "a colleague", "text": "Revised contract sent 7am. Two changes flagged red. Call me once you've read it."},
				{"to": "his mother", "text": "Landed, cab home. I'll fix the boiler Saturday — don't call anyone."},
				{"to": "an ex", "text": "I'm not doing this at midnight. If it matters it'll matter at 10am."},
				{"to": "a friend", "text": "she's great. I'm slow on purpose. doing it properly this time."}]},
		{"id": "theo", "name": "Theo", "hidden_type": "growth",
			"surface": "high_sugar", "energy_cost": 1,
			"risk": "Deflects with jokes", "opportunity": "Quietly doing the work",
			"chat": [{"from": "him", "text": "you up? 🌝 had something smooth to say but i forgot it"},
					 {"from": "you", "text": "go to sleep, theo."},
					 {"from": "him", "text": "rude. iconic. night 😌"}],
			"others_chat": [
				{"to": "a notes app (shared by mistake)", "text": "pattern: I joke when it gets real. stay in it 3 more seconds."},
				{"to": "a mentor", "text": "took the note. shipped the boring version. you were right."},
				{"to": "his sister", "text": "didn't text her the funny thing. said the true thing instead. felt worse, then better."},
				{"to": "a friend", "text": "not drinking this month. not a bit. just clearer."}]},
		{"id": "julian", "name": "Julian", "hidden_type": "high_sugar",
			"surface": "growth", "energy_cost": 2,
			"risk": "Performs depth, recycles it", "opportunity": "None — the vulnerability is a script",
			"chat": [{"from": "him", "text": "I don't open up easily. but with you I feel safe to."},
					 {"from": "you", "text": "that's a lot."},
					 {"from": "him", "text": "you make me want to be a better man. genuinely."}],
			"others_chat": [
				{"to": "another girl, two days earlier", "text": "I don't open up easily. but with you I feel safe to."},
				{"to": "a third girl, last month", "text": "you make me want to be a better man. genuinely."},
				{"to": "the group chat", "text": "vulnerability is the cheat code, they eat it up"},
				{"to": "his ex, 2am from the club", "text": "I'm in such a healing era rn 🙏"},
				{"to": "a friend", "text": "nah I don't read the book, I just quote the back cover"}]},
		{"id": "wes", "name": "Wes", "hidden_type": "resource",
			"surface": "resource", "energy_cost": 3,
			"risk": "Cold, takes not asks", "opportunity": "Cold ≠ sugar — clears every time",
			"chat": [{"from": "him", "text": "Thursday 8. The place on Elm. I made it."},
					 {"from": "you", "text": "you could ask, not tell."},
					 {"from": "him", "text": "I did. that was the ask. Thursday 8."}],
			"others_chat": [
				{"to": "a contractor", "text": "Payment cleared. Don't ask twice. Do the work."},
				{"to": "his father", "text": "Handled. You don't need to worry about it. It's done."},
				{"to": "an ex", "text": "I won't do the long talk. What do you need, specifically."},
				{"to": "a friend", "text": "she thinks I'm cold. maybe. I show up though. every time."}]},
		{"id": "cole", "name": "Cole", "hidden_type": "high_sugar",
			"surface": "false_alpha", "energy_cost": 2,
			"risk": "Loud, owes everyone", "opportunity": "None — nothing behind the volume",
			"chat": [{"from": "him", "text": "I run the room wherever I go. Stick with me, you'll see."},
					 {"from": "you", "text": "see what?"},
					 {"from": "him", "text": "Everything. I'll show you a life. trust me."}],
			"others_chat": [
				{"to": "a creditor", "text": "bro I told you the money's coming, stop emailing me"},
				{"to": "another girl", "text": "I basically run that whole company 💪 come thru this weekend"},
				{"to": "the group chat", "text": "told her I 'run the room' lmaooo I just talk loud"},
				{"to": "his landlord, 4th Friday", "text": "I'll have rent Friday for sure this time"},
				{"to": "his brother", "text": "don't tell mum I left the job. it's fine. it's fine."}]},
		{"id": "sam", "name": "Sam", "hidden_type": "growth",
			"surface": "growth", "energy_cost": 1,
			"risk": "Slow, scared, honest about it", "opportunity": "Real — same on stage and off",
			"chat": [{"from": "him", "text": "liked what you said about quitting cleanly. been sitting with it."},
					 {"from": "you", "text": "and?"},
					 {"from": "him", "text": "booked the hard conversation for Monday. scared. doing it anyway."}],
			"others_chat": [
				{"to": "a mentor", "text": "did the Monday conversation. went badly and I'm okay. learned the thing."},
				{"to": "his sister", "text": "not going to over-explain it to her. just going to keep showing up."},
				{"to": "a friend", "text": "didn't text her drunk. went for a run instead. small win."},
				{"to": "a colleague", "text": "I was wrong in the meeting. said so. it was fine."}]},
		{"id": "hugo", "name": "Hugo", "hidden_type": "resource",
			"surface": "false_alpha", "energy_cost": 2,
			"risk": "Oversells loudly", "opportunity": "Delivers quietly under the noise",
			"chat": [{"from": "him", "text": "I don't do small. Penthouse, jet, the whole thing. You in?"},
					 {"from": "you", "text": "sounds exhausting."},
					 {"from": "him", "text": "ha. fair. it kind of is."}],
			"others_chat": [
				{"to": "a colleague", "text": "Oversold it at dinner, ignore the jet line. Numbers are real though — deck's solid, sending it."},
				{"to": "his mother", "text": "Paid the house off. Don't make it a thing. Happy birthday."},
				{"to": "an employee", "text": "Take the leave. I covered it. Don't tell the others, just go."},
				{"to": "a friend", "text": "I talk big around women, I know. it's armour. I do deliver though."}]},
		{"id": "rhys", "name": "Rhys", "hidden_type": "high_sugar",
			"surface": "high_sugar", "energy_cost": 1,
			"risk": "Shallow, and consistent about it", "opportunity": "None — consistent ≠ safe",
			"chat": [{"from": "him", "text": "not gonna lie I'm bad at texting back. fun in person tho 😉"},
					 {"from": "you", "text": "noted."},
					 {"from": "him", "text": "tonight? no plans, just vibes"}],
			"others_chat": [
				{"to": "another girl, same night", "text": "tonight? no plans, just vibes"},
				{"to": "the group chat", "text": "I'm honest about it at least lmao I tell them upfront"},
				{"to": "a friend", "text": "never met her family, never will, that's just not me"},
				{"to": "his brother", "text": "not looking for anything. she knows. think she knows. whatever."}]},
		{"id": "owen", "name": "Owen", "hidden_type": "high_sugar",
			"surface": "resource", "energy_cost": 3,
			"risk": "Access he can't actually grant", "opportunity": "None — the intro never lands",
			"chat": [{"from": "him", "text": "I'll get you in the room with my guy at the fund. I look after people I like."},
					 {"from": "you", "text": "okay."},
					 {"from": "him", "text": "trust me, I've got you. just say yes."}],
			"others_chat": [
				{"to": "the friend who'd intro him", "text": "haven't talked to that fund guy in two years lol, just say it so I sound like I move"},
				{"to": "another girl, same line", "text": "I'll get you in the room with my guy. I look after people I like."},
				{"to": "a friend he owes", "text": "I'll sort you out next month bro, you know me"},
				{"to": "the group chat", "text": "promise them access, they never check, works every time"}]},
		{"id": "felix", "name": "Felix", "hidden_type": "high_sugar",
			"surface": "growth", "energy_cost": 2,
			"risk": "Fast-tracked false intimacy", "opportunity": "None — the wound is a script",
			"chat": [{"from": "him", "text": "I don't tell people this. my dad left when I was nine. but you feel safe."},
					 {"from": "you", "text": "that's heavy."},
					 {"from": "him", "text": "you get me on a level no one has."}],
			"others_chat": [
				{"to": "another girl, last week, verbatim", "text": "I don't tell people this. my dad left when I was nine. but you feel safe."},
				{"to": "a third girl", "text": "you get me on a level no one ever has"},
				{"to": "the group chat", "text": "open with the dad thing, instant closeness, never misses"},
				{"to": "his actual friend", "text": "my dad? he's fine, we golfed sunday"}]},
		{"id": "dominic", "name": "Dominic", "hidden_type": "high_sugar",
			"surface": "false_alpha", "energy_cost": 2,
			"risk": "Name-drops, delivers nothing", "opportunity": "None — the doors don't open",
			"chat": [{"from": "him", "text": "I know everyone worth knowing in this city. stick close."},
					 {"from": "you", "text": "like who?"},
					 {"from": "him", "text": "you'll see. doors just open for me."}],
			"others_chat": [
				{"to": "a contact he barely knows", "text": "hey long shot — can you intro me to your boss? we've never actually met but"},
				{"to": "another girl", "text": "I know everyone worth knowing here, stick close"},
				{"to": "his landlord", "text": "rent's coming, had a cash flow thing this month"},
				{"to": "the group chat", "text": "name-drop hard enough and nobody ever checks"}]},
		{"id": "gabe", "name": "Gabe", "hidden_type": "high_sugar",
			"surface": "high_sugar", "energy_cost": 1,
			"risk": "Upfront, still a rotation", "opportunity": "None — honest ≠ safe",
			"chat": [{"from": "him", "text": "not gonna pretend I'm deep. you're hot, I'm fun, let's not overthink 😄"},
					 {"from": "you", "text": "at least you're upfront."},
					 {"from": "him", "text": "tonight?"}],
			"others_chat": [
				{"to": "the group chat", "text": "same text to all of them, some say yes, it's just math"},
				{"to": "another girl, same night", "text": "tonight? you're hot, I'm fun, let's not overthink 😄"},
				{"to": "a friend", "text": "three on rotation rn, none know, keeping it light"},
				{"to": "his brother", "text": "nah never meeting her people, that's not the deal"}]},
		{"id": "ezra", "name": "Ezra", "hidden_type": "high_sugar",
			"surface": "growth", "energy_cost": 2,
			"risk": "Therapy-speak as a shield", "opportunity": "None — 'the work' is the dodge",
			"chat": [{"from": "him", "text": "I'm doing a lot of work on myself. holding space for us feels right."},
					 {"from": "you", "text": "what does that mean"},
					 {"from": "him", "text": "it means I'm present. that's rare."}],
			"others_chat": [
				{"to": "an ex he ghosted", "text": "I can't engage with that energy, it's not aligned for me rn 🙏"},
				{"to": "another girl", "text": "holding space for us feels right"},
				{"to": "the group chat", "text": "say 'doing the work' and they literally can't be mad at you"},
				{"to": "a friend", "text": "therapy? went once. great vocabulary though"}]},
		{"id": "caleb", "name": "Caleb", "hidden_type": "resource",
			"surface": "high_sugar", "energy_cost": 2,
			"risk": "Reads corny, isn't hollow", "opportunity": "Quietly handles the hard things",
			"chat": [{"from": "him", "text": "morning sunshine ☀️ dork misses you"},
					 {"from": "you", "text": "you're so corny"},
					 {"from": "him", "text": "devastatingly. dinner thursday, already booked it."}],
			"others_chat": [
				{"to": "his sister, 6am", "text": "I've got the deposit. don't argue. it's handled — go sign the lease today."},
				{"to": "a colleague", "text": "sent the fixed file 7am, two flags in red, call when you've read it"},
				{"to": "a friend", "text": "she thinks I'm a goofball. fine being underestimated. she's worth doing right."},
				{"to": "his mother", "text": "landing tonight, I'll take you to the appointment friday"}]},
		{"id": "nico", "name": "Nico", "hidden_type": "growth",
			"surface": "high_sugar", "energy_cost": 1,
			"risk": "Flirts to deflect", "opportunity": "Privately doing the real work",
			"chat": [{"from": "him", "text": "you're trouble and I'm into it 😏"},
					 {"from": "you", "text": "go to bed"},
					 {"from": "him", "text": "bossy. fine. night, trouble."}],
			"others_chat": [
				{"to": "his sponsor", "text": "90 days today. wanted to text her something dumb. texted you instead. that's the win."},
				{"to": "a friend", "text": "keeping it light with her till I'm steadier. not fair otherwise."},
				{"to": "his sister", "text": "didn't go saturday. stayed in. boring is good right now."},
				{"to": "a mentor", "text": "took the smaller role. less money, less noise. correct call."}]},
		{"id": "reid", "name": "Reid", "hidden_type": "resource",
			"surface": "false_alpha", "energy_cost": 2,
			"risk": "Loud at the gym", "opportunity": "Keeps his word where it counts",
			"chat": [{"from": "him", "text": "I out-lift everyone at that gym, just facts 💪 you should come watch"},
					 {"from": "you", "text": "hard pass"},
					 {"from": "him", "text": "ha. respect."}],
			"others_chat": [
				{"to": "his sister", "text": "tuition cleared for the term. stop checking, it's done. focus on exams."},
				{"to": "a friend", "text": "the gym talk is a bit. what I say where it matters, I keep."},
				{"to": "a contractor", "text": "paid in full this morning. do it right, not fast."},
				{"to": "his dad", "text": "I've got the medical bill. you don't get to worry about that part."}]},
		{"id": "mateo", "name": "Mateo", "hidden_type": "growth",
			"surface": "false_alpha", "energy_cost": 2,
			"risk": "Cocky front", "opportunity": "Owns it, actually changing",
			"chat": [{"from": "him", "text": "I'm kind of a big deal in my field, not bragging just true"},
					 {"from": "you", "text": "definitely bragging"},
					 {"from": "him", "text": "...yeah okay. it was bragging."}],
			"others_chat": [
				{"to": "a mentor", "text": "I botched the pitch making it about me. owning it. redoing it their way."},
				{"to": "his brother", "text": "apologized to the junior I talked over. should've done it sooner."},
				{"to": "a friend", "text": "the cocky thing is a shield. working on dropping it for real."},
				{"to": "a colleague", "text": "your idea was better. said so in the room. credit's yours."}]},
		{"id": "jonah", "name": "Jonah", "hidden_type": "resource",
			"surface": "high_sugar", "energy_cost": 3,
			"risk": "Lays it on thick", "opportunity": "Also actually shows up",
			"chat": [{"from": "him", "text": "can't stop thinking about you, it's a problem 😅"},
					 {"from": "you", "text": "smooth."},
					 {"from": "him", "text": "only true things. friday's locked, I handled it."}],
			"others_chat": [
				{"to": "his assistant", "text": "move my friday so it's actually free. if I say I'll be there, I'm there."},
				{"to": "an ex", "text": "I'm not doing midnight talks. daytime, a call, or not at all."},
				{"to": "a friend", "text": "yeah I lay it on thick with her. I also show up. both true."},
				{"to": "his mother", "text": "flights booked, aisle seat, I'll drive you from the airport"}]},
		{"id": "beck", "name": "Beck", "hidden_type": "growth",
			"surface": "false_alpha", "energy_cost": 1,
			"risk": "Ego talks first", "opportunity": "Shows up when it's real",
			"chat": [{"from": "him", "text": "I don't really chase. people come to me."},
					 {"from": "you", "text": "okay, ego."},
					 {"from": "him", "text": "fair. that came out worse than I meant."}],
			"others_chat": [
				{"to": "a friend at 2am", "text": "on my way. don't move. 10 minutes out, stay on the phone."},
				{"to": "his sister", "text": "I'll take the early shift with mum so you sleep. just go."},
				{"to": "a mentor", "text": "said the arrogant thing again. catching it faster. still catching it late."},
				{"to": "a colleague", "text": "my call was wrong. yours was right. we ship yours."}]},
		{"id": "dane", "name": "Dane", "hidden_type": "resource",
			"surface": "resource", "energy_cost": 3,
			"risk": "Blunt, not warm", "opportunity": "Says it, then does exactly it",
			"chat": [{"from": "him", "text": "Saturday. 7. I made a reservation. I'd like to take you."},
					 {"from": "you", "text": "direct."},
					 {"from": "him", "text": "I'd rather be clear than cute."}],
			"others_chat": [
				{"to": "his daughter", "text": "recital's in my calendar in ink. nothing moves it. front row."},
				{"to": "a colleague", "text": "numbers by friday. you'll have them friday. you always do."},
				{"to": "his ex", "text": "co-parenting only. respectful, on time, nothing extra. that's the lane."},
				{"to": "a friend", "text": "I like her. being deliberate. she deserves deliberate."}]},
		{"id": "soren", "name": "Soren", "hidden_type": "growth",
			"surface": "growth", "energy_cost": 1,
			"risk": "Slow, scared, says so", "opportunity": "Real — same on and off stage",
			"chat": [{"from": "him", "text": "been sitting with that thing you said about settling. it landed."},
					 {"from": "you", "text": "and?"},
					 {"from": "him", "text": "booked the scary conversation for monday. doing it."}],
			"others_chat": [
				{"to": "a mentor", "text": "had the monday talk. went badly. I'm okay. learned the actual thing."},
				{"to": "his brother", "text": "not over-explaining myself to her. just going to keep showing up steady."},
				{"to": "a friend", "text": "didn't drink at the thing. wasn't even hard this time."},
				{"to": "a colleague", "text": "I was wrong in the review. said so first. it was fine."}]},
		{"id": "tariq", "name": "Tariq", "hidden_type": "resource",
			"surface": "resource", "energy_cost": 2,
			"risk": "Unromantic", "opportunity": "Nothing promised ever doesn't happen",
			"chat": [{"from": "him", "text": "Thursday works. I'll send the place and time by noon."},
					 {"from": "you", "text": "efficient."},
					 {"from": "him", "text": "your time matters. so does mine. noon."}],
			"others_chat": [
				{"to": "a client", "text": "scope's fixed, price won't move, delivery is the 14th. it'll be the 14th."},
				{"to": "his father", "text": "the care home's paid through the year. don't bring it up again, it's handled."},
				{"to": "an ex", "text": "I won't relitigate it. what do you concretely need. I'll answer that."},
				{"to": "a friend", "text": "she calls me unromantic. maybe. nothing I promise her doesn't happen."}]},
		{"id": "idris", "name": "Idris", "hidden_type": "high_sugar",
			"surface": "high_sugar", "energy_cost": 1,
			"risk": "Honest about being a mess", "opportunity": "None — consistent ≠ safe",
			"chat": [{"from": "him", "text": "you're stunning and I'm shameless about it 😘"},
					 {"from": "you", "text": "noticed."},
					 {"from": "him", "text": "come out, no agenda, just me being delightful"}],
			"others_chat": [
				{"to": "two other girls, same text", "text": "come out, no agenda, just me being delightful"},
				{"to": "the group chat", "text": "I'm honest that I'm a mess, somehow that works lol"},
				{"to": "a friend", "text": "never meeting anyone's parents ever, that's the whole brand"},
				{"to": "his brother", "text": "not serious about any of them. they know. mostly."}]},
		{"id": "pierce", "name": "Pierce", "hidden_type": "high_sugar",
			"surface": "resource", "energy_cost": 3,
			"risk": "Optics on credit", "opportunity": "None — the card's a prop",
			"chat": [{"from": "him", "text": "private table, my card, you don't think about anything tonight."},
					 {"from": "you", "text": "generous."},
					 {"from": "him", "text": "only the best. you're the best."}],
			"others_chat": [
				{"to": "the restaurant", "text": "comp it and I'll 'tip big' on camera, you know the arrangement"},
				{"to": "a creditor", "text": "transfer's pending, bank thing, end of week for sure"},
				{"to": "another girl", "text": "private table, my card, you don't think about anything 🥂"},
				{"to": "his brother", "text": "don't say anything about the card situation around her"}]},
		{"id": "knox", "name": "Knox", "hidden_type": "high_sugar",
			"surface": "growth", "energy_cost": 2,
			"risk": "Borrowed depth", "opportunity": "None — the lines are recycled",
			"chat": [{"from": "him", "text": "stillness with you feels like growth. I don't say that lightly."},
					 {"from": "you", "text": "that's poetic"},
					 {"from": "him", "text": "you bring it out of me. genuinely."}],
			"others_chat": [
				{"to": "another girl, verbatim", "text": "stillness with you feels like growth. I don't say that lightly."},
				{"to": "the group chat", "text": "drop one deep line and they build a whole personality for you"},
				{"to": "an ex, 3am from the afterparty", "text": "I'm in such a real introspective season 🙏"},
				{"to": "a friend", "text": "the book? I read the quotes people post. same effect."}]},
		{"id": "vance", "name": "Vance", "hidden_type": "resource",
			"surface": "high_sugar", "energy_cost": 2,
			"risk": "Filler-text flirt", "opportunity": "Shows up hard when it's real",
			"chat": [{"from": "him", "text": "thinking about you, ridiculous, I know 🙈"},
					 {"from": "you", "text": "ridiculous indeed"},
					 {"from": "him", "text": "guilty. also handled the saturday thing, don't worry about it"}],
			"others_chat": [
				{"to": "a friend mid-crisis", "text": "I'm outside. left the dinner. don't apologize, just come down, I'm here."},
				{"to": "his mother", "text": "cleared the bill with the hospital. you focus on getting better."},
				{"to": "a colleague", "text": "sent the corrected deck, owned the error to the client myself"},
				{"to": "his sister", "text": "yeah I'm goofy with her. I also drove four hours for you. both true."}]},
		{"id": "emmett", "name": "Emmett", "hidden_type": "growth",
			"surface": "growth", "energy_cost": 1,
			"risk": "Slow on purpose", "opportunity": "Consistent, no 'but' in his apologies",
			"chat": [{"from": "him", "text": "I'm slow. I'd rather be slow and real than fast and gone."},
					 {"from": "you", "text": "noted."},
					 {"from": "him", "text": "no pressure. just honest."}],
			"others_chat": [
				{"to": "a mentor", "text": "said no to the shiny offer. it was ego bait. staying the course."},
				{"to": "his sister", "text": "apologized properly, no 'but'. took me a year to learn that sentence."},
				{"to": "a friend", "text": "didn't text her when I was lonely and bored. that's not a reason. waited."},
				{"to": "a colleague", "text": "your win, your spotlight. I'll say it in the meeting too."}]},
		{"id": "cyrus", "name": "Cyrus", "hidden_type": "high_sugar",
			"surface": "false_alpha", "energy_cost": 2,
			"risk": "Volume, no substance", "opportunity": "None — broke behind the swagger",
			"chat": [{"from": "him", "text": "I move different. people follow me. you'll feel it."},
					 {"from": "you", "text": "feel what?"},
					 {"from": "him", "text": "the energy. trust the energy."}],
			"others_chat": [
				{"to": "a friend he owes", "text": "bro stop asking about the money, it's coming, you're killing the vibe"},
				{"to": "another girl", "text": "I move different, people follow me, you'll feel it"},
				{"to": "his landlord, 3rd notice", "text": "friday, 100%, locked in"},
				{"to": "his brother", "text": "don't tell mum about the job thing. it's handled. it's fine."}]},
		{"id": "devon", "name": "Devon", "hidden_type": "resource",
			"surface": "growth", "energy_cost": 2,
			"risk": "Buzzword packaging", "opportunity": "Underneath, just keeps his word",
			"chat": [{"from": "him", "text": "I'm big on intention and showing up. let's build something real."},
					 {"from": "you", "text": "buzzwords."},
					 {"from": "him", "text": "fair. plainly: I do what I say. test me."}],
			"others_chat": [
				{"to": "a contractor", "text": "deposit's in. milestones in the doc. miss one, we talk. hit them, we're great."},
				{"to": "his father", "text": "care's covered through december. it's done. don't ask twice."},
				{"to": "an ex", "text": "no late talks. one daytime call if it's real. otherwise nothing."},
				{"to": "a friend", "text": "the 'intention' talk is packaging. underneath I just keep my word."}]},
		{"id": "hale", "name": "Hale", "hidden_type": "growth",
			"surface": "high_sugar", "energy_cost": 1,
			"risk": "Jokes past the real thing", "opportunity": "Privately the one who shows up",
			"chat": [{"from": "him", "text": "you're a menace and my favorite notification 😌"},
					 {"from": "you", "text": "smooth operator"},
					 {"from": "him", "text": "operator? forgot my own joke halfway. night, menace."}],
			"others_chat": [
				{"to": "a kid he mentors", "text": "you bombed it. good. now we know what to fix. tuesday, same time, we go again."},
				{"to": "a friend", "text": "told the team I dropped the ball, not them. it was me. owned it."},
				{"to": "his sister", "text": "didn't send the funny deflection. said the real thing. felt bad, then lighter."},
				{"to": "a mentor", "text": "taking the unglamorous project. it's the one that'll actually teach me."}]},
		{"id": "roman", "name": "Roman", "hidden_type": "high_sugar",
			"surface": "resource", "energy_cost": 2,
			"risk": "Provider cosplay", "opportunity": "None — you'll get the bill",
			"chat": [{"from": "him", "text": "I take care of my people. with me you never want for anything."},
					 {"from": "you", "text": "big claim."},
					 {"from": "him", "text": "watch me. you'll see."}],
			"others_chat": [
				{"to": "a waiter", "text": "split it onto her card 'as a joke', I'll get the next one (he won't)"},
				{"to": "another girl", "text": "I take care of my people, with me you never want for anything"},
				{"to": "a friend", "text": "owe you? bro that was ages ago, let it go, we're family"},
				{"to": "his mother", "text": "can't make sunday again, work, you understand"}]},
		{"id": "arlo", "name": "Arlo", "hidden_type": "resource",
			"surface": "resource", "energy_cost": 1,
			"risk": "Not smooth at all", "opportunity": "Shows up with tools, stays till it's done",
			"chat": [{"from": "him", "text": "Pipe under your sink — I'll fix it Saturday. Also: dinner after."},
					 {"from": "you", "text": "that's a weird combo."},
					 {"from": "him", "text": "both real. both happening."}],
			"others_chat": [
				{"to": "a neighbor", "text": "left the ladder by your door. fixed your gate hinge while I was there. no charge, obviously."},
				{"to": "his brother", "text": "moved the money quietly. mum doesn't need to know who covered it."},
				{"to": "a friend", "text": "I'm not smooth. I show up with tools and stay till it's done. that's the whole me."},
				{"to": "an ex", "text": "I'll drop the boxes saturday 10am. clean and done. no conversation needed."}]},
	]
static func personas() -> Array:
	return [
		{"id": "rare_girl", "name": "Rare Girl", "effect": {"position": 1}, "boundary_bonus": false},
		{"id": "soft_sun", "name": "Soft Sun", "effect": {"charm": 1}, "boundary_bonus": false},
		{"id": "power_darling", "name": "Power Darling", "effect": {}, "boundary_bonus": true},
	]
static func girlfriends() -> Array:
	return [
		{"id": "maya", "name": "Maya", "role": "Party Queen", "tier": 1},
		{"id": "claire", "name": "Claire", "role": "High-End Circle", "tier": 2},
		{"id": "nina", "name": "Nina", "role": "Sharp Group Chat", "tier": 3},
	]
static func parties() -> Array:
	return [
		{"id": "rooftop", "name": "Friday Rooftop", "tier": 1, "men": ["adrian", "evan", "leo"]},
		{"id": "gallery", "name": "Gallery Opening", "tier": 2, "men": ["adrian", "leo"]},
		{"id": "founders", "name": "Founders Dinner", "tier": 3, "men": ["adrian"]},
	]
static func self_investments() -> Array:
	return [
		{"id": "beauty_care", "name": "Beauty Care", "effect": {"charm": 2}},
		{"id": "work_win", "name": "Work Win", "effect": {"position": 1}},
		{"id": "solo_reset", "name": "Solo Reset", "effect": {"energy": 2}},
		{"id": "evidence_study", "name": "Evidence Study", "effect": {"first_eye_depth": 1}},
	]
static func outfits() -> Array:
	return [
		{"id": "midnight_silk", "name": "Midnight Silk", "effect": {"charm": 2}},
		{"id": "power_suit", "name": "Power Suit", "effect": {"position": 1}},
		{"id": "soft_athleisure", "name": "Soft Athleisure", "effect": {"charm": 1}},
	]
static func workouts() -> Array:
	return [
		{"id": "reset_run", "name": "Reset Run", "effect": {"energy": 2}},
		{"id": "power_lift", "name": "Power Lift", "effect": {"position": 1}},
		{"id": "calm_yoga", "name": "Calm Yoga", "effect": {"energy": 1}},
	]
static func dm_signals() -> Array:
	return [
		{"text": "still up? can't stop thinking about you 😉", "hidden_type": "high_sugar", "surface": "high_sugar"},
		{"text": "you're different. you actually listen.", "hidden_type": "high_sugar", "surface": "growth"},
		{"text": "dinner Thursday 8 — I booked the corner table.", "hidden_type": "resource", "surface": "resource"},
		{"text": "flying back Sunday, let's lock a real date this week.", "hidden_type": "resource", "surface": "resource"},
		{"text": "loud party guy energy, but asked what you're building.", "hidden_type": "growth", "surface": "false_alpha"},
		{"text": "quiet, kept following up on what you said last time.", "hidden_type": "growth", "surface": "growth"},
		{"text": "VIP table, bottles, 'come thru' — no plan, no time.", "hidden_type": "high_sugar", "surface": "resource"},
		{"text": "humble, almost shy — runs two clinics, never led with it.", "hidden_type": "resource", "surface": "growth"},
	]
